### ISSUE TITLE
JSON unmarshal error with k8s 1.7 cluster

### ISSUE THREAD

**Issue by metahertz** [bakins/zfs-flex-volume#4]
**Issue Description**

First call to zfs-flex-volume (init) succeeds with no extra args as expected.

Second call to zfs-flex-volume is `getvolumename` with the following input JSON:
```
{"dataset":"test-volume","kubernetes.io/fsType":"","kubernetes.io/pvOrVolumeName":"test","kubernetes.io/readwrite":"rw","quota":"1G"}
```

Errors with a JSON unmarshal issue:

```
{"status":"Failed","message":"unable to unmarshal json: invalid character 'd' looking for beginning of object key string"}
```

Input (to k8s) is the example within the readme;
```
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "akins.org/zfs"
      options:
        dataset: "test-volume"
        quota: "1G"
```

Thanks.
